# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bool',
            field=models.BooleanField(default=False),
        ),
    ]
