# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_post_my_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.FileField(default=False, upload_to=b'uploads/%Y/%m/%d/'),
        ),
    ]
