# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_post_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.FileField(default=False, upload_to=b'uploads/%Y%m%d'),
        ),
    ]
