# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20170731_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[(b'S', b'Small'), (b'M', b'Medium'), (b'L', b'Large')], default=False, max_length=1),
        ),
    ]
