# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
