# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_auto_20170806_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreData',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('add_Time', models.DateTimeField(auto_now_add=True, verbose_name=b'date')),
                ('edit_Time', models.DateTimeField(auto_now=True, verbose_name=b'edit')),
                ('store_name', models.CharField(default=b'', max_length=20, verbose_name=b'store')),
                ('lat', models.CharField(default=b'', max_length=20, verbose_name=b'lat')),
                ('lng', models.CharField(default=b'', max_length=20, verbose_name=b'lng')),
                ('score', models.CharField(default=b'', max_length=10, verbose_name=b'score')),
            ],
        ),
    ]
