# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_mood_talk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='enabled',
        ),
    ]
