# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0014_remove_talk_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='nickname',
            field=models.CharField(default=b'\xe5\x8c\xbf\xe5\x90\x8d\xe8\x80\x85', max_length=10),
        ),
    ]
