# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0017_remove_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
